### ISSUE TITLE
QUESTION: Any reason for naming the build dir "obj"?

### ISSUE THREAD

**Issue by jrsmith3** [JasonHiebel/latex.makefile#1]
Did you have a reason for using a directory named "obj" as the build directory as opposed to, say, "build"?

Thanks for the great Makefile. I've been [using it](https://github.com/jrsmith3/latex_template) for more than a year; its been very helpful.

**Comment by JasonHiebel** [comment]
No real reason. 

In retrospect I think I was working on a lot of C and C++ at the time and so .obj files were on my mind. Perhaps bin or build would be more appropriate.

Thanks for the encouragement! There are still some problems I would like to work out and hopefully I'll have time this summer.

**Comment by jrsmith3** [comment]
Thanks for the response.
